export const exploreModePanoramas: any = {
    exp1: require(`@/assets/images/explore-pano/exp1.jpg`),
    exp2: require(`@/assets/images/explore-pano/exp2.jpg`),
    exp3: require(`@/assets/images/explore-pano/exp3.jpg`),
    exp4: require(`@/assets/images/explore-pano/exp4.jpg`),
    exp5: require(`@/assets/images/explore-pano/exp5.jpg`),
    exp6: require(`@/assets/images/explore-pano/exp6.jpg`),
    exp7: require(`@/assets/images/explore-pano/exp7.jpg`),
    exp8: require(`@/assets/images/explore-pano/exp8.jpg`),
    exp9: require(`@/assets/images/explore-pano/exp9.jpg`),
    exp10: require(`@/assets/images/explore-pano/exp10.jpg`),
    exp11: require(`@/assets/images/explore-pano/exp11.jpg`),
    exp12: require(`@/assets/images/explore-pano/exp12.jpg`),
    exp13: require(`@/assets/images/explore-pano/exp13.jpg`),
    exp14: require(`@/assets/images/explore-pano/exp14.jpg`),
    exp15: require(`@/assets/images/explore-pano/exp15.jpg`),
    exp16: require(`@/assets/images/explore-pano/exp16.jpg`),
};